baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2019.okfn.de" # the base hostname & protocol for your site, e.g. http://example.com

title: Tätigkeitsbericht des Open Knowledge Foundation Deutschland e.V. 2019
description: > # this means to ignore newlines until "show_exerpts:"
  Unser Tätigkeitsbericht enthält detaillierte Angaben zu den Entwicklungen unserer Organisation und unserer Projekte.
main_image: assets/images/intro/intro.png
show_excerpts: false # set to true to show excerpts on the homepage

license:
  holder: Open Knowledge Foundation Deutschland e.V.
  license: License CC BY-SA 4.0
mainpage:
  url: https://okfn.de
  #pdf: /fake/link/to.pdf
  label: Zurück zur OKF Website
  year: 2019
chapter:
  resources: Ressourcen
  effects:
    - label: Das Problem
      key: problem
    - label: Mögliche Ursachen
      key: causes
    - label: Lösungsansatz
      key: solution
    - label: Angestrebte Wirkung
      key: effect
  outcomes:
    - label: Erbrachte Leistungen
      key: achievements
    - label: Erbrachte Gesamtleistungen
      key: total_achievements
    - label: Output
      key: outputs
    - label: Outcome
      key: outcome
    - label: Impact
      key: impact
    - label: Evaluation
      key: evaluation
    - label: Ausblick
      key: outlook

matomo: no


# Build settings
markdown: kramdown
theme: okf-pub-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
